spring:
  datasource:
    url: &db_url jdbc:mysql://localhost:3306/FINAL_PROJECT
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: &db_username root
      password: &db_password dannyab59515951
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      show-sql: true
      hibernate:
        format_sql: true
        generate_statistics: true
logging:
  level:
    root: INFO
    org:
      hibernate:
        type: trace
        stat: DEBUG

